name: Deploy Dev Environment  # Nom du workflow pour le développement

on:
  push:
    branches:
      - dev  # Déclenchement du workflow lorsque des changements sont poussés vers la branche dev

jobs:
  deploy:
    runs-on: ubuntu-latest  # Spécifie l’environnement de la machine virtuelle pour exécuter les jobs

    steps:
      - name: Checkout code  # Étape de vérification du code source
        uses: actions/checkout@v2  # Action pour cloner le dépôt

      - name: Deploy to GitHub Pages (Dev)  # Étape de déploiement vers GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Action de déploiement pour GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Utilise le token GitHub pour autoriser le déploiement
          publish_dir: ./  # Spécifie le dossier de publication, ici la racine du dépôt
          destination_dir: dev  # Déploie les fichiers dans le dossier `/dev` sur la branche `gh-pages`
